-- Post-deployment schema changes. init-db runs this file last, after 001-003, on every run.
--
-- Convention: once a release of npd-loader has been deployed, NEVER edit the CREATE TABLE statements in 00x
-- files to change an existing table (CREATE TABLE IF NOT EXISTS skips tables that already exist, so the change
-- would silently not reach existing databases). Instead append idempotent statements here, for example:
--
--   ALTER TABLE <<schema>>.practitioner ADD COLUMN IF NOT EXISTS new_column text;
--
-- Changes to a partitioned parent propagate to every release partition. New columns appear in the v_* views
-- because init-db recreates them after running this file. After upgrading npd-loader, run `npd-loader init-db`.
--
-- (No migrations yet.)
