-- css_catalog_local DDL, from pg_dump --schema-only of the production server (PostgreSQL 16.11),
-- with owners and grants removed. Note master_warehouse_run's integer key is `id`; its `run_id` is a
-- uuid, and data_file.run_id references master_warehouse_run.id.
CREATE TABLE public.data_file (
    id integer NOT NULL,
    run_id integer NOT NULL,
    file_set character varying(500),
    file_type character varying(500),
    source_uri character varying(2000),
    source_version_name character varying(500),
    source_version_num character varying(500),
    file_name character varying(2000),
    file_rel_path character varying(2000),
    run_type_root_dir character varying(2000),
    parent_file integer,
    file_size bigint,
    file_hash character varying(1000),
    date_loaded timestamp without time zone,
    date_modified timestamp without time zone,
    date_created timestamp without time zone,
    exceptions character varying(8000)
);

ALTER TABLE public.data_file ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.data_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.master_warehouse_run (
    id integer NOT NULL,
    parent_run_id integer,
    run_type character varying(200) NOT NULL,
    run_id uuid DEFAULT gen_random_uuid() NOT NULL,
    completion_status character varying(2000),
    date_completed timestamp without time zone,
    date_started timestamp without time zone DEFAULT LOCALTIMESTAMP,
    notes character varying(4000),
    run_description character varying(200),
    result character varying(2000),
    "user" character varying(50) DEFAULT SESSION_USER NOT NULL,
    xml_config xml,
    xml_output xml,
    project character varying(1000),
    run_class character varying(100)
);

ALTER TABLE public.master_warehouse_run ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.master_warehouse_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.data_file
    ADD CONSTRAINT pk_data_file PRIMARY KEY (id);

ALTER TABLE ONLY public.master_warehouse_run
    ADD CONSTRAINT pk_master_warehouse_run PRIMARY KEY (id);

CREATE INDEX ix_data_file_parent_file ON public.data_file USING btree (parent_file);

CREATE INDEX ix_data_file_run_id ON public.data_file USING btree (run_id);

ALTER TABLE ONLY public.data_file
    ADD CONSTRAINT fk_data_file_parent_file FOREIGN KEY (parent_file) REFERENCES public.data_file(id);

ALTER TABLE ONLY public.data_file
    ADD CONSTRAINT fk_data_file_run_id FOREIGN KEY (run_id) REFERENCES public.master_warehouse_run(id);

ALTER TABLE ONLY public.master_warehouse_run
    ADD CONSTRAINT fk_master_warehouse_run_parent_run_id FOREIGN KEY (parent_run_id) REFERENCES public.master_warehouse_run(id);
